spring.application.name=auth-service

#server
server.port=8081

#Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#JWT Secret
jwt.secret=${JWT_SECRET}
jwt.access.expiration=900000
jwt.refresh.expiration=604800000

internal.security.key=${INTERNAL_SECURITY_KEY}


# Disable the stack trace in the API response
server.error.include-stacktrace=never
# Also hide the exception message if you want it even cleaner
server.error.include-message=always
# Remove the 'exception' class name from the response
server.error.include-exception=false
